kind: Pod
apiVersion: v1
metadata:
  name: functionswithaksakvdemo
spec:
  containers:
    - name: functionswithaksakvdemopod
      image: ustdemoacr.azurecr.io/storagetriggerfuncwithakv:latest
      volumeMounts:
      - name: secrets-store01-inline
        mountPath: "/mnt/secrets-store"
        readOnly: true
  volumes:
    - name: secrets-store01-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure-funcakvaksdemo"