# This is a SecretProviderClass example using system-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-system-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"    # Set to true for using managed identity
    userAssignedIdentityID: "c18b3ae9-0de6-4756-ad25-0106e7f9186e"      # If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: "ustdemoazkv"
    cloudName: ""                   # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: AzureWebJobsStorage
          objectType: secret        # object types: secret, key, or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: storageconstr
          objectType: secret
          objectVersion: ""
    tenantId: "35475cd9-ec8d-40b3-b3e2-ae71174569a2"           # The tenant ID of the key vault
    secretName: mysecret